from datetime import datetime

USER_COLLECTION = "user"
ROLE_COLLECTION = "role"
PERMISSION_COLLECTION = "permission"
HOTEL_COLLECTION = "hotel_collection"
ACCOMODATION_COLLECTION = "accomodation"
ROOOM_INVENTORY_COLLECTION = "room_inventory"
DAILY_RATES_COLLECTION = "daily_rate"
RESERVATION_COLLECTION = "reservation"

RESERVATION_STATUS_PENDING = "pending"
RESERVATION_STATUS_CONFIRMED = "confirmed"
RESERVATION_STATUS_CANCELLED = "cancelled"

RESERVATION_STATUS_ENUM = {
    1: RESERVATION_STATUS_PENDING,
    2: RESERVATION_STATUS_CONFIRMED,
    3: RESERVATION_STATUS_CANCELLED
}

PERMISSION_INVENTORY_ADD = "inventory.add"
PERMISSION_ACCOMMODATION_ADD = "accommodation.add"
PERMISSION_HOTEL_ADD = "hotel.add"
PERMISSION_RESERVATION_VIEW = "reservation.view"
PERMISSION_VIEW_INVETORY = "inventory.view"
PERMISSION_RESERVATION_CONFIRM = "reservation.confirm"

ROLE_ENUM = {
    1: "CEO",
    2: "MANAGER",
    3: "STAFF"
}

ROLE_TO_PERMISSION_MAPPING = {
    1: [PERMISSION_INVENTORY_ADD, PERMISSION_VIEW_INVETORY,
        PERMISSION_ACCOMMODATION_ADD, PERMISSION_HOTEL_ADD, PERMISSION_RESERVATION_VIEW,
        PERMISSION_RESERVATION_CONFIRM],
    2: [PERMISSION_INVENTORY_ADD, PERMISSION_VIEW_INVETORY,
        PERMISSION_ACCOMMODATION_ADD, PERMISSION_HOTEL_ADD],
    3: [PERMISSION_RESERVATION_VIEW, PERMISSION_RESERVATION_CONFIRM]
}


def convert_date(date_str):
    return datetime.strptime(date_str, "%Y-%m-%d")


if __name__ == "__main__":
    print(convert_date("2019-07-19"))